/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NutricionistaRouteImport } from './routes/nutricionista'
import { Route as PacienteIndexRouteImport } from './routes/paciente.index'
import { Route as PacienteProgresoRouteImport } from './routes/paciente.progreso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricionistaRoute = NutricionistaRouteImport.update({
  id: '/nutricionista',
  path: '/nutricionista',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteIndexRoute = PacienteIndexRouteImport.update({
  id: '/paciente/',
  path: '/paciente/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteProgresoRoute = PacienteProgresoRouteImport.update({
  id: '/paciente/progreso',
  path: '/paciente/progreso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nutricionista': typeof NutricionistaRoute
  '/paciente/progreso': typeof PacienteProgresoRoute
  '/paciente/': typeof PacienteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nutricionista': typeof NutricionistaRoute
  '/paciente/progreso': typeof PacienteProgresoRoute
  '/paciente': typeof PacienteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nutricionista': typeof NutricionistaRoute
  '/paciente/progreso': typeof PacienteProgresoRoute
  '/paciente/': typeof PacienteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nutricionista' | '/paciente/progreso' | '/paciente/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nutricionista' | '/paciente/progreso' | '/paciente'
  id: '__root__' | '/' | '/nutricionista' | '/paciente/progreso' | '/paciente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NutricionistaRoute: typeof NutricionistaRoute
  PacienteProgresoRoute: typeof PacienteProgresoRoute
  PacienteIndexRoute: typeof PacienteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricionista': {
      id: '/nutricionista'
      path: '/nutricionista'
      fullPath: '/nutricionista'
      preLoaderRoute: typeof NutricionistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/': {
      id: '/paciente/'
      path: '/paciente'
      fullPath: '/paciente/'
      preLoaderRoute: typeof PacienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/progreso': {
      id: '/paciente/progreso'
      path: '/paciente/progreso'
      fullPath: '/paciente/progreso'
      preLoaderRoute: typeof PacienteProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NutricionistaRoute: NutricionistaRoute,
  PacienteProgresoRoute: PacienteProgresoRoute,
  PacienteIndexRoute: PacienteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
