/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedNutricionistaRouteImport } from './routes/_authenticated/nutricionista'
import { Route as AuthenticatedPacienteIndexRouteImport } from './routes/_authenticated/paciente.index'
import { Route as AuthenticatedPacienteProgresoRouteImport } from './routes/_authenticated/paciente.progreso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNutricionistaRoute =
  AuthenticatedNutricionistaRouteImport.update({
    id: '/nutricionista',
    path: '/nutricionista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacienteIndexRoute =
  AuthenticatedPacienteIndexRouteImport.update({
    id: '/paciente/',
    path: '/paciente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacienteProgresoRoute =
  AuthenticatedPacienteProgresoRouteImport.update({
    id: '/paciente/progreso',
    path: '/paciente/progreso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nutricionista': typeof AuthenticatedNutricionistaRoute
  '/paciente/progreso': typeof AuthenticatedPacienteProgresoRoute
  '/paciente/': typeof AuthenticatedPacienteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nutricionista': typeof AuthenticatedNutricionistaRoute
  '/paciente/progreso': typeof AuthenticatedPacienteProgresoRoute
  '/paciente': typeof AuthenticatedPacienteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/nutricionista': typeof AuthenticatedNutricionistaRoute
  '/_authenticated/paciente/progreso': typeof AuthenticatedPacienteProgresoRoute
  '/_authenticated/paciente/': typeof AuthenticatedPacienteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nutricionista' | '/paciente/progreso' | '/paciente/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nutricionista' | '/paciente/progreso' | '/paciente'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/nutricionista'
    | '/_authenticated/paciente/progreso'
    | '/_authenticated/paciente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nutricionista': {
      id: '/_authenticated/nutricionista'
      path: '/nutricionista'
      fullPath: '/nutricionista'
      preLoaderRoute: typeof AuthenticatedNutricionistaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paciente/': {
      id: '/_authenticated/paciente/'
      path: '/paciente'
      fullPath: '/paciente/'
      preLoaderRoute: typeof AuthenticatedPacienteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paciente/progreso': {
      id: '/_authenticated/paciente/progreso'
      path: '/paciente/progreso'
      fullPath: '/paciente/progreso'
      preLoaderRoute: typeof AuthenticatedPacienteProgresoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNutricionistaRoute: typeof AuthenticatedNutricionistaRoute
  AuthenticatedPacienteProgresoRoute: typeof AuthenticatedPacienteProgresoRoute
  AuthenticatedPacienteIndexRoute: typeof AuthenticatedPacienteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNutricionistaRoute: AuthenticatedNutricionistaRoute,
  AuthenticatedPacienteProgresoRoute: AuthenticatedPacienteProgresoRoute,
  AuthenticatedPacienteIndexRoute: AuthenticatedPacienteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
